# Generated by Django 3.2.4 on 2021-06-14 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate_Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliate_gender', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Type_Affiliate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_affiliate_description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Type_Identitynumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeid_description', models.CharField(max_length=250)),
                ('typeid_acronym', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Main_affiliate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('second_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('secondlast_name', models.CharField(max_length=250)),
                ('identity_number', models.CharField(max_length=250)),
                ('date_affiliate', models.DateField()),
                ('date_created', models.DateField()),
                ('is_main_affiliate', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('gender', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Domain.affiliate_gender')),
                ('identitynumber_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Domain.type_identitynumber')),
                ('main_affiliate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Domain.main_affiliate')),
                ('type_affiliate', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Domain.type_affiliate')),
            ],
        ),
    ]
