# Generated by Django 3.2.4 on 2021-06-14 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Domain', '0002_alter_main_affiliate_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_affiliate',
            name='main_affiliate_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Domain.main_affiliate'),
        ),
    ]
